### ISSUE TITLE
Error when running HTML checks: HTML5Outline is not define

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#108]
Sometimes Ace fails with the following stack trace:

```
 Error when running HTML checks: Error: Evaluation failed: ReferenceError: HTML5Outline is not defined
    at Object.ace.getHTMLOutline (/Users/Me/.config/yarn/global/node_modules/ace-core/dist/scripts/ace-extraction.js:126:3)
    at Object.ace.createReport (/Users/Me/.config/yarn/global/node_modules/ace-core/dist/scripts/ace-extraction.js:13:30)
    at /Users/Me/.config/yarn/global/node_modules/ace-core/dist/scripts/ace-axe.js:112:17
    at d (/Users/Me/.config/yarn/global/node_modules/axe-core/axe.min.js:12:26128)
```

This was reported by @amesga and I could reproduce. To be investigated.

**Comment by rdeltour** [comment]
The issue comes from errors in the bundled JS that prevents Ace-injected scripts to run. We should mitigate that by at least showing a warning, and if possible retry a second time with all the scripts disabled.
