### ISSUE TITLE
NodeJS version requirement

### ISSUE THREAD

**Issue by josteinaj** [daisy/ace#117]
ACE works fine on my computer, but when I installed on a server I got this:

```
$ /usr/bin/ace -o /tmp/ace /tmp/561824.epub --verbose
verbose: ACE cwd=/tmp, outdir=/tmp/ace, tmpdir=undefined, verbose=true, silent=false, jobId=
info:    Processing /tmp/561824.epub
verbose: Extracting EPUB
info:    Parsing EPUB
verbose: at location '/tmp/tmp-110750It2lpY6uvzN'
info:    Analyzing accessibility metadata
info:    Checking package...
error:   Unexpected error: spawn EACCES
debug:   Error: spawn EACCES
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at Object.exports.spawn (child_process.js:369:9)
    at Function.<anonymous> (/usr/lib/node_modules/ace-core/node_modules/puppeteer/node6/Launcher.js:126:40)
    at next (native)
    at step (/usr/lib/node_modules/ace-core/node_modules/puppeteer/node6/Launcher.js:70:24)
    at Promise.resolve.then.value (/usr/lib/node_modules/ace-core/node_modules/puppeteer/node6/Launcher.js:81:15)
info:    Closing logs.
Re-run Ace using the --verbose option to enable full debug logging.
```

The server has nodejs version v6.12.0 while my computer has v8.9.1. The installation instructions says that nodejs v6 should be sufficient. But I suppose this means that I need a newer version of nodejs? A similar error here suggests that I need NodeJS v7.4+: https://github.com/astefanutti/decktape/issues/112

**Comment by josteinaj** [comment]
Hmm, I updated to nodejs 8 on the server but I still get the error. Will continue troubleshooting.

**Comment by josteinaj** [comment]
So it was something with permissions in the global installation directory. It looks the same as on my computer so I'm not quite sure why it didn't work, but this fixed it:

```bash
sudo chown -R `whoami` /usr/lib/node_modules
```

So probably I didn't need to upgrade to nodejs 8 then.
