### ISSUE TITLE
Unexpected error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by polizoto** [daisy/ace#175]
ACE's error message says that container.xml was not found, yet the file exists. 

I am running the ACE 1.0 on a macOS High Sierra v. 10.13.3.

Note: This EPUB was unzipped, edited, and re-zipped for post-processing. It seems as though this process adds temporary files to my EPUB? Such as the following path:

`'/var/folders/mt/0y0k05w92vx304ps6xxqpvb00000gn/T/tmp-220026bBuF7cAtXsX'`

The entire log is as follows:

`ace EPUB3_book.epub -o ./report  --force --verbose
verbose: Ace 1.0.0, Node v9.9.0, Darwin 17.4.0
verbose: Options: cwd=/Users/jpolizzotto/Desktop/Epub_Workflow, outdir=./report, tmpdir=undefined, verbose=true, silent=false, jobId=
info:    Processing EPUB3_book.epub
verbose: Extracting EPUB
info:    Parsing EPUB
verbose: at location '/var/folders/mt/0y0k05w92vx304ps6xxqpvb00000gn/T/tmp-220026bBuF7cAtXsX'
error:   Failed to parse EPUB
error:   Unexpected error: ENOENT: no such file or directory, open '/var/folders/mt/0y0k05w92vx304ps6xxqpvb00000gn/T/tmp-220026bBuF7cAtXsX/META-INF/container.xml'
debug:   Error: ENOENT: no such file or directory, open '/var/folders/mt/0y0k05w92vx304ps6xxqpvb00000gn/T/tmp-220026bBuF7cAtXsX/META-INF/container.xml'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at EpubParser.calculatePackageDocPath (/usr/local/lib/node_modules/@daisy/ace/node_modules/@daisy/epub-utils/lib/epub-parse.js:176:22)
    at Promise (/usr/local/lib/node_modules/@daisy/ace/node_modules/@daisy/epub-utils/lib/epub-parse.js:111:33)
    at new Promise (<anonymous>)
    at EpubParser.parse (/usr/local/lib/node_modules/@daisy/ace/node_modules/@daisy/epub-utils/lib/epub-parse.js:110:10)
    at Promise (/usr/local/lib/node_modules/@daisy/ace/node_modules/@daisy/epub-utils/lib/epub.js:108:41)
    at new Promise (<anonymous>)
    at EPUB.parse (/usr/local/lib/node_modules/@daisy/ace/node_modules/@daisy/epub-utils/lib/epub.js:106:12)
    at epub.extract.then (/usr/local/lib/node_modules/@daisy/ace/node_modules/@daisy/ace-core/lib/core/ace.js:56:36)
info:    Closing logs.`

**Comment by polizoto** [comment]
Used wrong process to zip files into EPUB. This works on macOS:

`zip -r -X "../EPUB3_book.zip" *`
