### ISSUE TITLE
Concurrent Requests Failing with following errors in aws ecs fargate

### ISSUE THREAD

**Issue by puspbhatt** [daisy/ace#356]
**We have daisy ace running in aws ecs fargate.
ace version: 1.2.2
ace-http: 1.2.2
npm version: 6.14.13
node version: v14.17.1
baseimage: ubuntu:20.04 
java8 **

{ Error: Protocol error (Target.closeTarget): Target closed. at Promise (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:63) at new Promise (<anonymous>) at Connection.send (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:70:16) at Page.close (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1199:44) at Object.run (/usr/local/lib/node_modules/@daisy/ace/node_modules/@daisy/ace-axe-runner-puppeteer/lib/index.js:123:20) at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Protocol error (Target.closeTarget): Target closed.' }

[31merror[39m: Ace HTML check error: Failed to check Content Document 'xhtml/urn_pearson_manifestation_e50397ed-2aa5-4363-b934-5afaf36f1c38.xhtml': Protocol error (Target.closeTarget): Target closed.

{ Error: Protocol error (Runtime.callFunctionOn): Target closed. at Promise (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63) at new Promise (<anonymous>) at CDPSession.send (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16) at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:201:50) at ExecutionContext.evaluate (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:27) at DOMWorld.evaluate (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:91:24) at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Protocol error (Runtime.callFunctionOn): Target closed.' } { Error: Protocol error (Runtime.callFunctionOn): Target closed. at Promise (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63) at new Promise (<anonymous>) at CDPSession.send (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16) at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:201:50) at ExecutionContext.evaluate (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:27) at DOMWorld.evaluate (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:91:24) at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Protocol error (Runtime.callFunctionOn): Target closed.' }

{ Error: Protocol error (Runtime.callFunctionOn): Target closed. at Promise (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63) at new Promise (<anonymous>) at CDPSession.send (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16) at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:201:50) at ExecutionContext.evaluate (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:27) at DOMWorld.evaluate (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:91:24) at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Protocol error (Runtime.callFunctionOn): Target closed.' } { Error: Protocol error (Runtime.callFunctionOn): Target closed. at Promise (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63) at new Promise (<anonymous>) at CDPSession.send (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16) at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:201:50) at ExecutionContext.evaluateHandle (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:152:21) at DOMWorld.addScriptTag (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:182:35) message: 'Protocol error (Runtime.callFunctionOn): Target closed.' }

[31merror[39m: Ace HTML check error: Failed to check Content Document 'xhtml/urn_pearson_manifest_400dfeac-3e1e-418e-8049-d00550a3b9ed.xhtml': Protocol error (Runtime.callFunctionOn): Target closed.
[32minfo[39m: Consolidating results...
[32minfo[39m: Copying data
[31merror[39m: Ace processing error: Error: Failed to check Content Document 'xhtml/urn_pearson_manifestation_e50397ed-2aa5-4363-b934-5afaf36f1c38.xhtml': Protocol error (Target.closeTarget): Target closed.
[31merror[39m: Ace processing error: Error: Failed to check Content Document 'xhtml/urn_pearson_manifest_400dfeac-3e1e-418e-8049-d00550a3b9ed.xhtml': Protocol error (Runtime.callFunctionOn): Target closed.
TypeError: Cannot read property 'internal' of undefined
at ace.then.catch.jobid (/usr/local/lib/node_modules/@daisy/ace/node_modules/@daisy/ace-http/lib/index.js:195:57)

**Comment by mahanthesh** [comment]
I am also getting same error on concurrent requests processing in aws fargate.

(/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:91:24) at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Protocol error (Runtime.callFunctionOn): Target closed.' } { Error: Protocol error (Runtime.callFunctionOn): Target closed. at Promise (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63) at new Promise () at CDPSession.send (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16) at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:201:50) at ExecutionContext.evaluateHandle (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:152:21) at DOMWorld.addScriptTag (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:182:35) message: 'Protocol error (Runtime.callFunctionOn): Target closed.' }
